name: Delete Merged Branches

on:
  push:
    branches:
      - main  # Replace with your main branch name (e.g., main or master)

jobs:
  delete-merged-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete merged branches
        run: |
          git fetch --prune
          git branch --merged | grep 'feature/' | xargs -n 1 git branch -d
