name: Delete Merged Feature Branches

on:
  push:
    branches:
      - main  # Trigger on push events to the main branch

jobs:
  delete-merged-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete merged feature branches
        run: |
          git fetch --prune
          git branch --merged | grep 'feature/' | xargs -n 1 git branch -d
